---

- name: Install base packages
  become: yes
  apt:
    name:
    - 'netcat'
    - 'libpcre3-dev'
    - 'libssl-dev'
    - 'zlib1g-dev'
    state: present

- name: Install nginx
  import_tasks: nginx.yml

- name: Install systemd deamons
  import_tasks: systemd.yml
  when: ansible_service_mgr == 'systemd'
