---

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

# Run the equivalent of "apt-get update"
- name: update package definitions
  apt:
    update_cache: yes

- name: install apt-transport-https
  become: yes
  apt:
    name: "apt-transport-https"
    state: present

- name: install base packages
  become: yes
  apt:
    name:
    - gcc
    - make
    - vim
    - htop
    - unzip
    - pass
    - tree
    - netcat
    - iftop
    state: present
