all:
  hosts:
    myserver:
      public_ip: 10.20.30.40
      private_ip: 10.20.30.41
    raspberrypi:
      public_ip: 50.60.70.80
      private_ip: 192.168.0.10
  children:
    servers:
      hosts:
        myserver:
          ansible_host: 10.20.30.40
          ansible_port: 22
          ansible_user: changeme
    cameras:
      hosts:
        raspberrypi:
          ansible_host: 192.168.0.10
          ansible_port: 22
          ansible_user: changeme
          ansible_password: changeme
          ansible_python_interpreter: /usr/bin/python3
