---

- name: Set tmpfs
  import_tasks: tmpfs.yml

# Run the equivalent of "apt-get update" as a separate step
- name: Update package definitions
  apt:
    update_cache: yes

- name: Install base packages
  become: yes
  apt:
    name: ['vim', 'htop', 'tree', 'iftop', 'git']
    state: present

- name: Install stream
  import_tasks: ffmpeg.yml
